language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install pip -U
  - pip install -r requirements.txt -U
script:
  - python3 -m xdoctest kata
after_success:
  - codecov
notifications:
  email: false
